import { apiClient } from './client';
import { LiveEmployeeTracking, RoutePoint, AssignedVisit } from '../types';

export const fetchLiveEmployees = async (): Promise<LiveEmployeeTracking[]> => {
  try {
    const response = await apiClient.get<LiveEmployeeTracking[]>('/v2/employees/live');
    return response.data;
  } catch {
    const now = Date.now();
    const routeAhmed: RoutePoint[] = [
      {
        id: 'pt-1',
        shift_id: 'sh-101',
        shiftId: 'sh-101',
        latitude: 31.4800,
        longitude: 74.3200,
        accuracy_meters: 10,
        gpsAccuracyMeters: 10,
        altitude_meters: 210,
        speed_mps: 4.5,
        bearing_degrees: 90,
        device_timestamp: new Date(now - 3600000).toISOString(),
        deviceTimestamp: new Date(now - 3600000).toISOString(),
        recorded_timestamp: new Date(now - 3600000).toISOString(),
        is_mock: false,
        received_at: new Date(now - 3590000).toISOString(),
        created_at: new Date(now - 3590000).toISOString(),
      },
      {
        id: 'pt-2',
        shift_id: 'sh-101',
        shiftId: 'sh-101',
        latitude: 31.4851,
        longitude: 74.3262,
        accuracy_meters: 12,
        gpsAccuracyMeters: 12,
        altitude_meters: 211,
        speed_mps: 2.1,
        bearing_degrees: 45,
        device_timestamp: new Date(now - 1800000).toISOString(),
        deviceTimestamp: new Date(now - 1800000).toISOString(),
        recorded_timestamp: new Date(now - 1800000).toISOString(),
        is_mock: false,
        received_at: new Date(now - 1790000).toISOString(),
        created_at: new Date(now - 1790000).toISOString(),
      },
      {
        id: 'pt-3',
        shift_id: 'sh-101',
        shiftId: 'sh-101',
        latitude: 31.5000,
        longitude: 74.3400,
        accuracy_meters: 13,
        gpsAccuracyMeters: 13,
        altitude_meters: 212,
        speed_mps: 5.0,
        bearing_degrees: 120,
        device_timestamp: new Date(now - 25000).toISOString(),
        deviceTimestamp: new Date(now - 25000).toISOString(),
        recorded_timestamp: new Date(now - 25000).toISOString(),
        is_mock: false,
        received_at: new Date(now - 20000).toISOString(),
        created_at: new Date(now - 20000).toISOString(),
      },
    ];

    const visitsAhmed: AssignedVisit[] = [
      {
        id: 'vst-1',
        assignment_id: 'asgn-1',
        assignmentId: 'asgn-1',
        location_id: 'loc-1',
        locationId: 'loc-1',
        location_name: 'Metro Cash & Carry (Model Town)',
        locationName: 'Metro Cash & Carry (Model Town)',
        location_code: 'LOC-101',
        locationCode: 'LOC-101',
        latitude: 31.4851,
        longitude: 74.3262,
        location: {
          id: 'loc-1',
          name: 'Metro Cash & Carry (Model Town)',
          code: 'LOC-101',
          address: 'Block M, Model Town, Lahore',
          latitude: 31.4851,
          longitude: 74.3262,
          active: true,
        },
        status: 'DELIVERED',
        delivered_at: new Date(now - 1800000).toISOString(),
        deliveredAt: new Date(now - 1800000).toISOString(),
        verified_distance_meters: 18,
        verifiedDistanceMeters: 18,
        gps_accuracy_meters: 12,
        gpsAccuracyMeters: 12,
      },
      {
        id: 'vst-2',
        assignment_id: 'asgn-1',
        assignmentId: 'asgn-1',
        location_id: 'loc-2',
        locationId: 'loc-2',
        location_name: 'Hyperstar Supermarket (Gulberg)',
        locationName: 'Hyperstar Supermarket (Gulberg)',
        location_code: 'LOC-102',
        locationCode: 'LOC-102',
        latitude: 31.5085,
        longitude: 74.3524,
        location: {
          id: 'loc-2',
          name: 'Hyperstar Supermarket (Gulberg)',
          code: 'LOC-102',
          address: 'MM Alam Road, Gulberg III, Lahore',
          latitude: 31.5085,
          longitude: 74.3524,
          active: true,
        },
        status: 'PENDING',
        delivered_at: null,
        deliveredAt: null,
        verified_distance_meters: null,
        verifiedDistanceMeters: null,
        gps_accuracy_meters: null,
        gpsAccuracyMeters: null,
      },
    ];

    const routeBilal: RoutePoint[] = [
      {
        id: 'pt-10',
        shift_id: 'sh-102',
        shiftId: 'sh-102',
        latitude: 31.4722,
        longitude: 74.3792,
        accuracy_meters: 25,
        gpsAccuracyMeters: 25,
        altitude_meters: 215,
        speed_mps: 1.2,
        bearing_degrees: 180,
        device_timestamp: new Date(now - 180000).toISOString(),
        deviceTimestamp: new Date(now - 180000).toISOString(),
        recorded_timestamp: new Date(now - 180000).toISOString(),
        is_mock: false,
        received_at: new Date(now - 170000).toISOString(),
        created_at: new Date(now - 170000).toISOString(),
      },
    ];

    const visitsBilal: AssignedVisit[] = [
      {
        id: 'vst-4',
        assignment_id: 'asgn-2',
        assignmentId: 'asgn-2',
        location_id: 'loc-4',
        locationId: 'loc-4',
        location_name: 'Esajee & Co. (DHA Phase 3)',
        locationName: 'Esajee & Co. (DHA Phase 3)',
        location_code: 'LOC-104',
        locationCode: 'LOC-104',
        latitude: 31.4722,
        longitude: 74.3792,
        location: {
          id: 'loc-4',
          name: 'Esajee & Co. (DHA Phase 3)',
          code: 'LOC-104',
          address: 'Y Block Market, DHA Phase 3, Lahore',
          latitude: 31.4722,
          longitude: 74.3792,
          active: true,
        },
        status: 'DELIVERED',
        delivered_at: new Date(now - 180000).toISOString(),
        deliveredAt: new Date(now - 180000).toISOString(),
        verified_distance_meters: 12,
        verifiedDistanceMeters: 12,
        gps_accuracy_meters: 25,
        gpsAccuracyMeters: 25,
      },
    ];

    return [
      {
        employee_id: 'emp-1',
        employeeId: 'emp-1',
        employee_name: 'Ahmed Khan',
        employeeName: 'Ahmed Khan',
        employee_code: 'EMP-001',
        employeeCode: 'EMP-001',
        shift_status: 'ACTIVE',
        shiftStatus: 'ACTIVE',
        shift_start_time: new Date(now - 3600000).toISOString(),
        shiftStartTime: new Date(now - 3600000).toISOString(),
        last_location: routeAhmed[routeAhmed.length - 1],
        latestLocation: routeAhmed[routeAhmed.length - 1],
        last_seen_at: new Date(now - 25000).toISOString(),
        lastSeenAt: new Date(now - 25000).toISOString(),
        freshness: 'FRESH',
        delivered_count: 2,
        deliveredCount: 2,
        assigned_count: 3,
        assignedCount: 3,
        pendingCount: 1,
        missedCount: 0,
        route_points: routeAhmed,
        routePoints: routeAhmed,
        assigned_visits: visitsAhmed,
        assignedVisits: visitsAhmed,
      },
      {
        employee_id: 'emp-2',
        employeeId: 'emp-2',
        employee_name: 'Bilal Ahmed',
        employeeName: 'Bilal Ahmed',
        employee_code: 'EMP-002',
        employeeCode: 'EMP-002',
        shift_status: 'ACTIVE',
        shiftStatus: 'ACTIVE',
        shift_start_time: new Date(now - 7200000).toISOString(),
        shiftStartTime: new Date(now - 7200000).toISOString(),
        last_location: routeBilal[routeBilal.length - 1],
        latestLocation: routeBilal[routeBilal.length - 1],
        last_seen_at: new Date(now - 180000).toISOString(),
        lastSeenAt: new Date(now - 180000).toISOString(),
        freshness: 'STALE',
        delivered_count: 1,
        deliveredCount: 1,
        assigned_count: 2,
        assignedCount: 2,
        pendingCount: 1,
        missedCount: 0,
        route_points: routeBilal,
        routePoints: routeBilal,
        assigned_visits: visitsBilal,
        assignedVisits: visitsBilal,
      },
      {
        employee_id: 'emp-3',
        employeeId: 'emp-3',
        employee_name: 'Hamza Ali',
        employeeName: 'Hamza Ali',
        employee_code: 'EMP-003',
        employeeCode: 'EMP-003',
        shift_status: 'COMPLETED',
        shiftStatus: 'COMPLETED',
        shift_start_time: new Date(now - 28800000).toISOString(),
        shiftStartTime: new Date(now - 28800000).toISOString(),
        last_location: null,
        latestLocation: null,
        last_seen_at: new Date(now - 3600000).toISOString(),
        lastSeenAt: new Date(now - 3600000).toISOString(),
        freshness: 'OFFLINE',
        delivered_count: 2,
        deliveredCount: 2,
        assigned_count: 3,
        assignedCount: 3,
        pendingCount: 0,
        missedCount: 1,
        route_points: [],
        routePoints: [],
        assigned_visits: [],
        assignedVisits: [],
      },
    ];
  }
};

export const fetchLiveTracking = fetchLiveEmployees;

export const fetchEmployeeLiveDetails = async (employeeId: string): Promise<LiveEmployeeTracking | null> => {
  const all = await fetchLiveEmployees();
  const found = all.find((e) => e.employeeId === employeeId || e.employee_id === employeeId);
  return found || all[0];
};
