from datetime import datetime
from uuid import UUID
from pydantic import BaseModel, ConfigDict, Field, field_validator


class LocationCreateItem(BaseModel):
    """Schema for a single GPS location record in a batch upload."""

    id: UUID = Field(..., description="Location record UUID generated by Android")
    shift_id: UUID = Field(..., description="Shift UUID this location belongs to")
    latitude: float = Field(..., ge=-90.0, le=90.0, description="Latitude between -90 and 90")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="Longitude between -180 and 180")
    accuracy_meters: float | None = Field(default=None, description="Accuracy in meters (>= 0)")
    altitude_meters: float | None = Field(default=None, description="Altitude in meters")
    speed_mps: float | None = Field(default=None, description="Speed in meters/second (>= 0)")
    bearing_degrees: float | None = Field(default=None, description="Bearing in degrees (0 to 360)")
    device_timestamp: datetime = Field(..., description="Timestamp when point was recorded on device")
    recorded_timestamp: datetime | None = Field(default=None, description="Optional recorded timestamp on device")
    is_mock: bool = Field(default=False, description="Flag indicating if mock provider was used")

    @field_validator("accuracy_meters")
    @classmethod
    def validate_accuracy(cls, v: float | None) -> float | None:
        if v is not None and v < 0:
            raise ValueError("accuracy_meters must not be negative")
        return v

    @field_validator("speed_mps")
    @classmethod
    def validate_speed(cls, v: float | None) -> float | None:
        if v is not None and v < 0:
            raise ValueError("speed_mps must not be negative")
        return v

    @field_validator("bearing_degrees")
    @classmethod
    def validate_bearing(cls, v: float | None) -> float | None:
        if v is not None and (v < 0 or v > 360):
            raise ValueError("bearing_degrees must be between 0 and 360 degrees")
        return v


class LocationBatchCreate(BaseModel):
    """Schema for batch location upload request."""

    locations: list[LocationCreateItem] = Field(..., description="List of location records (max 500)")

    @field_validator("locations")
    @classmethod
    def validate_batch_size(cls, v: list[LocationCreateItem]) -> list[LocationCreateItem]:
        if not v:
            raise ValueError("Location batch cannot be empty")
        if len(v) > 500:
            raise ValueError("Batch size exceeds maximum limit of 500 records")
        return v


class LocationBatchResponse(BaseModel):
    """Schema for location batch response informing Android sync state."""

    received: int = Field(..., description="Total location records received in request")
    inserted: int = Field(..., description="Number of new location records inserted")
    duplicates: int = Field(..., description="Number of duplicate location records skipped")
    rejected: int = Field(default=0, description="Number of rejected location records")
    accepted_ids: list[UUID] = Field(..., description="List of all location UUIDs accepted (inserted + existing duplicates)")


class LocationResponse(BaseModel):
    """Response schema for single location item."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    shift_id: UUID
    latitude: float
    longitude: float
    accuracy_meters: float | None = None
    altitude_meters: float | None = None
    speed_mps: float | None = None
    bearing_degrees: float | None = None
    device_timestamp: datetime
    recorded_timestamp: datetime | None = None
    is_mock: bool
    received_at: datetime
    created_at: datetime
